### ISSUE TITLE
模型训练问题

### ISSUE THREAD

**Issue by zhenyuan1234** [RQ-Wu/RIDCP#17]
你好，我在自己的数据上重新训练的时候出现了以下错误，请问应该如何解决，谢谢！
  0%|          | 0/500 [00:00<?, ?image/s]Traceback (most recent call last):
  File "basicsr/train.py", line 243, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 236, in train_pipeline
    model.validation(val_loader, current_iter, tb_logger, opt['val']['save_img'])
  File "/home/qyj/DCP/basicsr/models/base_model.py", line 48, in validation
    self.nondist_validation(dataloader, current_iter, tb_logger, save_img, save_as_dir)
  File "/home/qyj/DCP/basicsr/models/dehaze_vq_model.py", line 266, in nondist_validation
    sr_img = tensor2img(self.output)
  File "/home/qyj/DCP/basicsr/utils/img_util.py", line 60, in tensor2img
    raise TypeError(f'tensor or list of tensors expected, got {type(tensor)}')
TypeError: tensor or list of tensors expected, got <class 'tuple'>

**Comment by qianxule** [comment]
可以请问一下，如何解决这个问题吗

**Comment by loopsman** [comment]
sr_img = tensor2img(self.output[0]),加上这个”[0]“

**Comment by loopsman** [comment]
> 可以请问一下，如何解决这个问题吗

sr_img = tensor2img(self.output[0])
